title: My Blog
description: A simple and clean blog powered by Jekyll and Minimal Mistakes.
author: Levi Okur
url: "https://l-okur.github.io/mein-blog"
theme:      tale

permalink:  /:year-:month-:day/:title
paginate:   5